version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - apt-get install -y jq mysql-client
  pre_build:
    commands:
      - echo Running migrations and collectstatic...
      - python manage.py migrate
      - python manage.py collectstatic --noinput

  build:
    commands:
      - echo Build complete on `date`
      - mysql -P 3306 -h $ENDPOINT -u admin -p$DB_PASS


artifacts:
  files:
    - '**/*'
